- name: Overview
  href: index.md
- name: Prometheus
  href: prometheus/toc.yml
- name: Alertmanager
  href: alertmanager/index.md
- name: Grafana
  href: grafana/toc.yml
- name: Azure Monitor
  href: azure-monitor/toc.yml