- name: Apache HTTP Server
  href: apache/toc.yml
- name: Asterisk PBX
  href: asterisk/toc.yml
- name: Authentik
  href: authentik/toc.yml
- name: Docker
  href: docker/toc.yml
- name: Kubernetes
  href: kubernetes/toc.yml
- name: Nginx
  href: nginx/toc.yml
- name: PostgreSQL
  href: postgresql/toc.yml